### PR TITLE
Russian guide which describes Russian braille rules

### PR DESCRIPTION
**Pull request by Futyn-Maker**
Hello!
Here is the guide called "Mass braille distribution guide" which describes Russian braille definitions and rules.

This document haven't got ISBN.

I've already edited the README.md file.

Andrey

### CODE REVIEW

**Comment by bertfrees** [comment]
Looks good. One request: can you change the title to "Руководство по выпуску брайлевских изданий массового распространения" and put the English translation beneath it? Like so:

> _Title translated_: Mass braille distribution guide

I also wonder whether there is a better translation for it :-) Sounds a bit weird TBH. But I guess it's fine.

Have you got any other information about the publication maybe? A year? A place? A link to the website of the author could also be useful.

**Comment by Futyn-Maker** [comment]
Should I change the title in table of contents or the README.md file?

Speaking about the translation, I've translated it by myself. I don't know how I can call the guide which describes aspects of publishing braille books, besides it. "Mass" is meaning that this tutorial oriented on publishing usual literature, not special...

**Comment by bertfrees** [comment]
I mean in the README.md file.

OK now I understand better. So the "массового" belongs to the preceding word (изданий), not the following (распространения)? So it's more like "mainstream" or something? (I'm not a native English speaker either.)

**Comment by Futyn-Maker** [comment]
In Russian language "Массового" (Mass, adjective)  belongs to the following "Распространения" (distribution). But it means that publications ("Издания") are aimed at a mass audience :-)

**Comment by bertfrees** [comment]
OK :-) @egli Help us out here please.

**Comment by Futyn-Maker** [comment]
In fact "The tutorial about edition of braille publications which aimed at mass audience". But I understant that it's very stupid name for English language :-)

**Comment by bertfrees** [comment]
Fine by me.

**Comment by Futyn-Maker** [comment]
I've asked to my friend who knows English well, I'll commit the changes tomorrow, ok?

**Comment by Futyn-Maker** [comment]
Oops. I didn't want to close it, it was the mistake.

**Review by egli — APPROVED** [review]

**Comment by Futyn-Maker** [comment]
I hope it's OK now :-)

**Comment by bertfrees** [comment]
I liked your proposal from yesterday better :-). But it's fine. Not super important.

**Comment by Futyn-Maker** [comment]
Oh, I forgot to edit the title in the table of contents! Can it be remerged?

https://github.com/Futyn-Maker/braille-specs/commit/c77a259864e3f76fd910caa99fbb823fca58aeb4

**Comment by bertfrees** [comment]
No problem, I'll change it.

**Pull request merged**
